import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { CaughtByFigure } from "@/components/build-story/CaughtByFigure";
import { Callout } from "@/components/ui/Callout";
import { DatedEntry } from "@/components/ui/DatedEntry";
import { Figure } from "@/components/ui/Figure";
import { PageHeader } from "@/components/ui/PageHeader";
import {
  buildLogBySlug,
  buildLogs,
  buildStats,
  buildStory,
  buildStoryGallery,
  projectBySlug,
} from "@/lib/content/load";
import { renderMarkdown, resolveRepositoryLink } from "@/lib/mdx";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = canonical("/how-this-was-built", {
  title: "How this site was built",
  description: buildStory.copy.description,
});

/**
 * Pacific time, where the work happened: a merge late on 1 October UTC-7 is 2 October in UTC.
 * Assembled from parts as yyyy-mm-dd, since a locale's own date pattern can change with ICU.
 */
const day = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/Vancouver",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});
const fmt = (iso: string) => {
  const part = Object.fromEntries(
    day.formatToParts(new Date(iso)).map(({ type, value }) => [type, value]),
  );
  return `${part.year}-${part.month}-${part.day}`;
};

/** The synthesis category whose gates the page counts separately; renaming it fails the build. */
const REVIEW_CATEGORY = "review";

const section = "max-w-content mx-auto mt-20 px-5 sm:px-8";
const h2 = "scroll-mt-20 text-2xl";
/**
 * A paragraph's measure, without colour or margin: Tailwind orders two utilities for one property
 * by name, not by their order in the class list, so a variant passes its own instead of
 * appending one to `lead`.
 */
const measure = "max-w-prose leading-relaxed";
const lead = `text-ink-2 mt-3 ${measure}`;

/**
 * How This Site Was Built (DESIGN §2, §6; Session 8). Server-rendered only: the build logs are
 * read from docs/build-log/ at build time, each with its own page, and this page lists them
 * with their goals; the history numbers are the committed snapshot (DESIGN §5.6). Besides the
 * section headings and the sentence that frames those numbers, every sentence comes from
 * content/build-story.ts. Pull requests are plain text, since the pre-launch repository is
 * private. The synthesis's chart counts the item lists it is given; no count is typed.
 */
export default async function HowThisWasBuiltPage() {
  const { repository, transparency, synthesis } = buildStory;
  const project = projectBySlug(buildStory.caseStudy.projectSlug);
  if (!project?.deepPage || !project.aside || !project.disclaimer) {
    throw new Error(
      `case study "${buildStory.caseStudy.projectSlug}" needs a deep page, an aside and a disclaimer`,
    );
  }
  const logTitle = (slug: string) => {
    const entry = buildLogBySlug(slug);
    if (!entry) throw new Error(`build story: no build log "${slug}"`);
    return entry.short;
  };
  const goals = await Promise.all(
    buildLogs.map((entry) =>
      renderMarkdown(entry.goal, { from: "docs/build-log", repository: repository.url }),
    ),
  );
  const allItems = synthesis.categories.flatMap((c) => c.items);
  const added = allItems.filter((item) => item.added);
  const review = synthesis.categories.find((c) => c.id === REVIEW_CATEGORY);
  if (!review) throw new Error(`build story: no "${REVIEW_CATEGORY}" category to count`);
  const addedAfterReview = review.items.filter((item) => item.added).length;

  return (
    <>
      <PageHeader title="How this site was built" lede={buildStory.copy.lede} />

      <section className="max-w-content mx-auto px-5 sm:px-8" aria-labelledby="who-did-what">
        <h2 id="who-did-what" className={h2}>
          Who did what
        </h2>
        <div className="mt-6 grid gap-x-12 gap-y-8 md:grid-cols-2">
          <div>
            <h3 className="text-lg">Generated by Claude Code</h3>
            <ul className="text-ink mt-3 space-y-3 leading-relaxed">
              {transparency.generated.map((line) => (
                <li key={line} className="border-line border-l pl-4">
                  {line}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h3 className="text-lg">Decided, reviewed or rejected by Paige</h3>
            <ul className="text-ink mt-3 space-y-3 leading-relaxed">
              {transparency.paige.map((line) => (
                <li key={line} className="border-accent border-l pl-4">
                  {line}
                </li>
              ))}
            </ul>
          </div>
        </div>
        <p className={`text-ink-2 mt-8 ${measure}`}>{transparency.tools}</p>
      </section>

      <section className={section} aria-labelledby="plan">
        <h2 id="plan" className={h2}>
          The plan
        </h2>
        <p className={lead}>{buildStory.copy.plan}</p>
        <dl className="border-line divide-line mt-6 max-w-3xl divide-y border-y">
          {repository.planningDocs.map((doc) => (
            <div key={doc.file} className="grid gap-x-6 gap-y-1 py-3 sm:grid-cols-[14rem_1fr]">
              <dt>
                <a
                  className="link-accent font-mono text-[0.95rem]"
                  href={resolveRepositoryLink(doc.file, { from: "", repository: repository.url })}
                >
                  {doc.file}
                </a>
              </dt>
              <dd className="text-ink-2 leading-relaxed">{doc.description}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className={section} aria-labelledby="what-went-wrong">
        <h2 id="what-went-wrong" className={h2}>
          What went wrong, and what caught it
        </h2>
        {synthesis.draft ? <Callout title="Draft">{buildStory.copy.draft}</Callout> : null}
        <p className={lead}>{synthesis.intro}</p>
        <p className={lead}>{synthesis.bound}</p>

        <div className="max-w-3xl">
          <CaughtByFigure categories={synthesis.categories} number={1} logTitle={logTitle} />
        </div>

        <div className="mt-10 grid max-w-5xl gap-x-12 gap-y-10 md:grid-cols-2">
          <div>
            <h3 className="text-lg">Gates added because of a failure</h3>
            <p className={lead}>
              <span className="text-ink font-mono tabular-nums">{added.length}</span> of the{" "}
              <span className="text-ink font-mono tabular-nums">{allItems.length}</span> items ended
              in a new test, check or rule, and{" "}
              <span className="text-ink font-mono tabular-nums">{addedAfterReview}</span> of those
              came out of a review pass: {synthesis.added}
            </p>
            <details className="mt-4">
              <summary className="link-accent cursor-pointer">List them</summary>
              <ul className="mt-3 space-y-2 text-[0.95rem] leading-relaxed">
                {added.map((item, i) => (
                  <li key={i} className="border-line border-l pl-3">
                    <span className="text-ink">{item.added}</span>{" "}
                    <span className="text-ink-2">After: {item.what}</span>{" "}
                    <Link
                      className="link-accent text-ink-2 font-mono text-xs whitespace-nowrap"
                      href={`/how-this-was-built/${item.log}`}
                    >
                      {logTitle(item.log)}
                    </Link>
                  </li>
                ))}
              </ul>
            </details>
          </div>
          <div>
            <h3 className="text-lg">In the logs&apos; words</h3>
            {synthesis.quotes.map((quote) => (
              <blockquote
                key={quote.text}
                className="border-accent text-ink mt-4 border-l-2 pl-5 leading-relaxed"
              >
                <p>{quote.text}</p>
                <footer className="mt-1.5">
                  <Link
                    className="link-accent font-mono text-xs"
                    href={`/how-this-was-built/${quote.log}`}
                  >
                    {logTitle(quote.log)}
                  </Link>
                </footer>
              </blockquote>
            ))}
          </div>
          {(
            [
              ["What worked", synthesis.worked],
              ["What did not", synthesis.didNot],
            ] as const
          ).map(([heading, notes]) => (
            <div key={heading}>
              <h3 className="text-lg">{heading}</h3>
              <ul className="mt-3 space-y-3 leading-relaxed">
                {notes.map((note) => (
                  <li key={note.text} className="border-line border-l pl-4">
                    <span className="text-ink">{note.text}</span>{" "}
                    <span className="font-mono text-xs">
                      {note.logs.map((slug, i) => (
                        <span key={slug}>
                          {i > 0 ? ", " : null}
                          <Link
                            className="link-accent text-ink-2 whitespace-nowrap"
                            href={`/how-this-was-built/${slug}`}
                          >
                            {logTitle(slug)}
                          </Link>
                        </span>
                      ))}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      <section className={section} aria-labelledby="build-log">
        <h2 id="build-log" className={h2}>
          The build log
        </h2>
        <p className={lead}>{buildStory.statsSentence}</p>
        <p className={`text-ink mt-3 ${measure}`}>
          <span className="font-mono tabular-nums">{buildStats.mergedPullRequests}</span> pull
          requests merged between{" "}
          <time className="font-mono" dateTime={buildStats.firstMergedAt}>
            {fmt(buildStats.firstMergedAt)}
          </time>{" "}
          and{" "}
          <time className="font-mono" dateTime={buildStats.lastMergedAt}>
            {fmt(buildStats.lastMergedAt)}
          </time>
          , and <span className="font-mono tabular-nums">{buildStats.commits}</span> commits on the
          main branch, <span className="font-mono tabular-nums">{buildStats.mergeCommits}</span> of
          them merges. Snapshot of{" "}
          <time className="font-mono" dateTime={buildStats.fetchedAt}>
            {fmt(buildStats.fetchedAt)}
          </time>
          , {buildStory.statsNote}
        </p>
        <p className={lead}>{buildStory.copy.logs}</p>
        <ol className="mt-6" aria-label="Build log entries, oldest first">
          {buildLogs.map((entry, i) => (
            <li key={entry.slug}>
              <DatedEntry
                id={entry.slug}
                dates={entry.date}
                org={entry.kind}
                meta={entry.pr ? `PR #${entry.pr}` : undefined}
                headingLevel={3}
                heading={
                  <Link className="link-quiet" href={`/how-this-was-built/${entry.slug}`}>
                    {entry.name}
                  </Link>
                }
              >
                <div className="text-ink-2 [&_a]:link-accent mt-3 max-w-prose leading-relaxed [overflow-wrap:anywhere] [&_p]:my-0">
                  {goals[i]}
                </div>
                <p className="mt-3">
                  <Link className="link-accent" href={`/how-this-was-built/${entry.slug}`}>
                    Read the log<span className="sr-only">: {entry.title}</span>
                  </Link>
                </p>
              </DatedEntry>
            </li>
          ))}
        </ol>
      </section>

      <section className={section} aria-labelledby="screenshots">
        <h2 id="screenshots" className={h2}>
          Screenshots
        </h2>
        <p className={lead}>{buildStory.copy.gallery}</p>
        <div className="mt-2 grid gap-x-8 md:grid-cols-2">
          {buildStoryGallery.map((figure, i) => (
            <Figure
              key={figure.asset}
              number={i + 2}
              caption={figure.caption}
              source={`docs/screenshots, ${logTitle(figure.log)}`}
            >
              <Image
                src={`/${figure.image.path}`}
                alt={figure.image.alt}
                width={figure.image.width}
                height={figure.image.height}
                sizes="(min-width: 1152px) 34rem, (min-width: 768px) 46vw, 100vw"
                className="h-auto w-full"
              />
            </Figure>
          ))}
        </div>
      </section>

      <section className={section} aria-labelledby="case-study">
        <h2 id="case-study" className={h2}>
          Case study 1: {project.title}
        </h2>
        <p className={lead}>{buildStory.caseStudy.intro}</p>
        <Callout tone="caution" title={project.disclaimer} className="max-w-prose">
          {buildStory.caseStudy.disclaimerNote}
        </Callout>
        <p className={lead}>{project.tagline}.</p>
        {project.aside.paragraphs.map((paragraph) => (
          <p key={paragraph} className={lead}>
            {paragraph}
          </p>
        ))}
        <ul className="mt-4 flex flex-wrap gap-x-6 gap-y-1">
          {project.aside.links?.map((link) => (
            <li key={link.url}>
              <a className="link-accent" href={link.url}>
                {link.label}
              </a>
            </li>
          ))}
          <li>
            <Link className="link-accent" href={`/projects/${project.slug}`}>
              The {project.title} case study
            </Link>
          </li>
        </ul>
      </section>
    </>
  );
}
